# 头部菜单，title: link
menu:
  Whoami: /whoami/whoami.html
  Github: https://github.com/zhuxiaoyu415
  FaceBook: https://www.facebook.com/profile.php?id=100006061269113

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://music.163.com/song/media/outer/url?id=1296583188.mp3
  - http://music.163.com/song/media/outer/url?id=1296583189.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: https://img.xiaoxiaomo.com/blog/zhu/img/s15.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    enable: true #是否开启
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '625481e7a5964aa7bbf3'
    # 应用秘钥
    clientSecret: '1e7d3d8defbd81a7f44172890b2efa47a9aa4b2f'
    # issue仓库名
    repo: 'blog_comments'
    # Github名
    owner: 'zhuxiaoyu415'
    # Github名
    admin: ['zhuxiaoyu415']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Sarah

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: UA-129669487-1


# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
